-- GenStat Supabase Schema
-- Run this in the Supabase SQL Editor to create all tables and RLS policies.
-- Safe to re-run: uses IF NOT EXISTS and CREATE OR REPLACE throughout.

-- ── Tables ──────────────────────────────────────────────────────────────────

-- Single-row table holding the current generator state.
-- The monitoring service upserts row id=1 on every state change.
CREATE TABLE IF NOT EXISTS generator_status (
    id                              bigint PRIMARY KEY,
    updated_at                      timestamptz NOT NULL DEFAULT now(),
    current_state                   text,
    utility_voltage                 real,
    generator_voltage               real,
    generator_runtime_hours         real DEFAULT 0,
    last_exercise_at                timestamptz,
    last_outage_at                  timestamptz,
    last_outage_duration_seconds    int,
    exercise_schedule_check_needed  boolean DEFAULT false,
    last_service_hours              real,
    service_interval_hours          real DEFAULT 200,
    service_check_needed            boolean DEFAULT false
);

-- Append-only log of state transitions.
CREATE TABLE IF NOT EXISTS generator_events (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          timestamptz NOT NULL DEFAULT now(),
    previous_state      text,
    new_state           text,
    utility_voltage     real,
    generator_voltage   real,
    duration_seconds    int
);

-- Device tokens for APNs push notifications.
-- The iOS app upserts on (token) conflict; the monitoring service reads active tokens.
CREATE TABLE IF NOT EXISTS device_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       text NOT NULL UNIQUE,
    platform    text NOT NULL DEFAULT 'ios',
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ── Row Level Security ──────────────────────────────────────────────────────

ALTER TABLE generator_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE generator_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_tokens    ENABLE ROW LEVEL SECURITY;

-- generator_status: anon can read and write (monitoring service uses anon key)
CREATE POLICY "Allow anonymous read"  ON generator_status FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous write" ON generator_status FOR ALL    TO anon USING (true) WITH CHECK (true);

-- generator_events: anon can read and insert
CREATE POLICY "Allow anonymous read"   ON generator_events FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert" ON generator_events FOR INSERT TO anon WITH CHECK (true);

-- device_tokens: anon can read, insert, and update (for marking tokens inactive)
CREATE POLICY "Allow anonymous read"   ON device_tokens FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert" ON device_tokens FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anonymous update" ON device_tokens FOR UPDATE TO anon USING (true) WITH CHECK (true);

-- ── Migrations (safe to re-run) ───────────────────────────────────────────

-- Add service reminder columns to existing databases.
ALTER TABLE generator_status ADD COLUMN IF NOT EXISTS last_service_hours real;
ALTER TABLE generator_status ADD COLUMN IF NOT EXISTS service_interval_hours real DEFAULT 200;
ALTER TABLE generator_status ADD COLUMN IF NOT EXISTS service_check_needed boolean DEFAULT false;

-- ── Seed data ───────────────────────────────────────────────────────────────

-- Insert the single status row if it doesn't exist.
INSERT INTO generator_status (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
